// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deguupsknwyzwbaatxmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZ3V1cHNrbnd5endiYWF0eG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDE2MDIsImV4cCI6MjA2NDY3NzYwMn0.ltpn2Ss-B5UUg7SL6hNX6L2zkHA_7cqK8xdVtnYsJcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);